### ISSUE TITLE
DTD is prohibited

### ISSUE THREAD

**Issue by morrigan777** [davegreen/miscellaneous#1]
copied all files to C:\Windows\PolicyDefinitions and SYSVOL\sysvol\ZZZZ.lan\Policies\PolicyDefinitions on the DC. but if i want to edit a gpo and go to administrative templates i get an error:

encountered an error while parsing. DTD is prohibited.

the error comes 3 times, one for each admx

**Comment by davegreen** [comment]
Hello,

This error usually appears because the file was saved in the wrong format (as HTML, rather than the raw text, which can alter quote marks and some other characters). Which ADMX do you specifically need? I've tested these files on central stores for Server 2008 and 2012 R2 domain controllers, as well as local policy stores on Windows 7 and 10 client machines without issue.

If you use the raw link to save the content from (e.g. https://raw.githubusercontent.com/davegreen/miscellaneous/master/CustomADMX/SystemCenterEndpointProtection.admx and https://raw.githubusercontent.com/davegreen/miscellaneous/master/CustomADMX/en-US/SystemCenterEndpointProtection.adml) or download the repository zip (https://github.com/davegreen/miscellaneous/archive/master.zip) you may have more success.

Additionally, you should not install both SystemCenterEndpointProtection2012 and SystemCenterEndpointProtection ADMX files as they do the same thing (one is just for legacy reference and to prevent hyperlinks from breaking).

Hopefully this gives you some things to go on.

Thanks,
Dave Green

**Comment by morrigan777** [comment]
thanks that was the trick

**Comment by davegreen** [comment]
That's alright, I've done it myself a few times. Thanks for getting back to me.
